package Common;

public enum CommandType {
    ADD,
    REMOVE_BY_ID,
    SHOW,
    INFO,
    CLEAR,
    SUM_OF_CAPACITIES,
    PRINT_ENGINE_POWER_ASCENDING,
    PRINT_FUEL_TYPE_DESCENDING,
    EXIT,
    REMOVE_FIRST,
    REMOVE_HEAD,
    REMOVE_GREATER,
    EXECUTE_SCRIPT,
    UPDATE_ID,
    HELP,
    REGISTER,
    LOGIN,
    GET_NEXT_COORDINATES_ID,
    GET_NEXT_VEHICLE_ID
}
