DROP TABLE IF EXISTS vehicle_owners CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS coordinates;

DROP SEQUENCE IF EXISTS users_id_seq;
DROP SEQUENCE IF EXISTS vehicles_id_seq;
